### PR TITLE
Added /noinfo, /noerr, /q, /qq, /exit flags

### PR DESCRIPTION
**Pull request by snoozbuster**
Additionally, rewrote argument parsing.

### CODE REVIEW

**Comment by bkeiren** [comment]
Hey Alex,

Please have a look at [this commit](https://github.com/bkeiren/EasyImgur/commit/7ac77cf317a86bae5607199a52965af131b98ea9). There were some issues with the changes in the pulled code of which I'm surprised they are there at all... For example, the switch parsing code can't have worked in the original form because it wouldn't remove the leading `/` from the switch string, but then would try to find a matching key in the map (without the leading `/`). 

What's more, simply taking the original code and starting in portable mode would instantly give you the error that some command was not parsed.

In addition I also found an unused local variable which I had to remove.

Have you tested your code or done a clean-up pass before submitting the pull request? If not I would like to ask you to do so thoroughly in the future before making a pull request.

**Comment by snoozbuster** [comment]
Oh yeah, you're right! I was thinking for some reason that `switch_` would have chopped off the leading `/`. I'm not sure why I was thinking that, too much Python probably. What I should have used was a list comprehension, really, to select the switches and remove the leading slash. 

Sorry about that. School just started so I've been really busy. Won't happen again!

**Comment by bkeiren** [comment]
No worries, I test things like this before publishing a release anyway. Just make sure you test things as well before making pull requests.

(I'm going to presume you intend on turning programming into something related to a current or future job, so take my word when I say that it's really important that you have the self discipline to test your code before letting others play with it ;) )

**Comment by snoozbuster** [comment]
Yeah, usually I do, but I've been busy and it seemed like it should work, so... Hehe. I do need to get used to testing more, though.

**Pull request merged**
